name: odom
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - contourpy=1.2.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - filelock=3.13.1
  - freetype=2.12.1
  - fsspec=2023.10.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.2
  - ipython=8.21.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.1.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.5
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=7.1.0
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.2.1
  - overrides=7.4.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - platformdirs=4.2.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scipy=1.11.4
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - av==12.2.0
      - bottleneck==1.3.8
      - cycler==0.12.1
      - distro==1.9.0
      - djitellopy==2.5.0
      - dm-tree==0.1.8
      - fairlearn==0.10.0
      - flatbuffers==24.3.7
      - fonttools==4.49.0
      - fqdn==1.5.1
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.10.0
      - imageio==2.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jsonpointer==3.0.0
      - jupyterlab-widgets==3.0.11
      - keras==3.0.5
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libclang==16.0.6
      - lime==0.2.0.1
      - line-profiler==4.1.3
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.7
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - pandas==2.2.1
      - pip==24.1.1
      - protobuf==4.25.3
      - pymagsac==0.2.1
      - pyparsing==3.1.1
      - rich==13.7.1
      - scikit-build==0.17.6
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - seaborn==0.13.2
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - termcolor==2.4.0
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - webcolors==24.6.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xgboost==2.0.3

